language: java
dist: trusty
sudo: required
jdk:
  - oraclejdk8

before_script: openssl s_client -CApath /etc/ssl/certs/ -connect plugins.gradle.org:443 </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /tmp/gradle.crt; sudo keytool -importcert -noprompt -file /tmp/gradle.crt -trustcacerts -keystore $JAVA_HOME/jre/lib/security/cacerts -alias root -storepass changeit;

script: 
    - for mod in cadc-util cadc-log cadc-rest cadc-auth-restlet cadc-http-client cadc-keygen cadc-test-servlet; do 
        cd $mod; gradle --info build javadoc install || break -1; cd ..; 
      done
      
    - cd cadc-quality; gradle --info build install || exit -1; cd ..
        
    - for mod in cadc-util cadc-rest cadc-log; do
        cd $mod; gradle checkstyleMain || break -1; cd ..;
      done


